config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts

  resources :developments

  get '/new-developments' => 'developments#new_developments_index'

  root to: 'pages#home'

  get '/concierge' => 'pages#concierge'
  get '/concierge/sky-concierge' => 'pages#sky'
  get '/concierge/ocean-concierge' => 'pages#ocean'
  get '/concierge/executive-concierge' => 'pages#executive'
  get '/concierge/exotic-concierge' => 'pages#exotic'
  get '/concierge/time-management' => 'pages#time'
  get '/investments' => 'pages#investments'
  get '/investments/how-to-buy-a-house' => 'pages#house'
  get '/integral-service' => 'pages#integral'
  get '/integral-service/legal' => 'pages#legal'
  get '/integral-service/visa-eb5' => 'pages#visa'
  get '/integral-service/eb5-program' => 'pages#eb5'
  get '/integral-service/financing' => 'pages#financing'
  get '/team' => 'pages#team'
  get '/contact' => 'contacts#new', as: 'contact_email'
  get '/thanks' => 'pages#thanks'

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  after_create :contact_mailer

  def contact_mailer
    contact = self
    Mailer.contact_form(contact).deliver_now
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin_user!, only: [:index, :show, :edit, :update, :destroy]

  respond_to :html

  def index
    @contacts = Contact.all
    respond_with(@contacts)
  end

  def show
    respond_with(@contact)
  end

  def new
    @contact = Contact.new
    respond_with(@contact)
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to thanks_path
    else
      render :action => 'new'
    end
  end

  def update
    @contact.update(contact_params)
    respond_with(@contact)
  end

  def destroy
    @contact.destroy
    respond_with(@contact)
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:first, :last, :email, :cellphone, :interest, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <div class="row">
    <div class="col-sm-5 col-sm-offset-1">
        <%= f.text_field :first, class: 'form-control', placeholder: 'First Name' %>
        <br>
        <%= f.text_field :last, class: 'form-control', placeholder: "Last Name" %>
        <br>
    </div>
    <div class="col-sm-5">
      <%= f.text_field :email, class: 'form-control', placeholder: "Email" %>
      <br>
      <%= f.text_field :cellphone, class: 'form-control', placeholder: "Cell Phone" %>
    </div>
  </div>
  <div class="delimiter"></div>
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <p>What Are You Interested In?</p>
        <%= f.select :interest, nil, {prompt: 'Select One'}, {class: 'form-control'} do %>
          <% [['Investments'], ['Concierge'], ['New Developments'], ['Existing Developments'], ['Residence']].each do |i| %>
            <%= content_tag(:option, i.first) %>
          <% end %>
        <% end %>
    </div>
  </div>
  <div class="delimiter"></div>
  <div class="row">
    <div class="col-sm-10 col-md-offset-1">
      <%= f.text_area :message, class: 'form-control', :rows => "1", style: 'padding-bottom: 5px;', placeholder: "Message" %>
    </div>
  </div>

    <%= f.submit "SEND", class: 'btn btn-contact' %>

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Email</th>
      <th>Cellphone</th>
      <th>Interest</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first %></td>
        <td><%= contact.last %></td>
        <td><%= contact.email %></td>
        <td><%= contact.cellphone %></td>
        <td><%= contact.interest %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<section class="top-section">
  <div class="container-fluid v-align">
    <div class="row">
      <div class="col-md-12">
        <h1>CONTACT</h1>
        <hr>
        <p>USE THE FORM</p>
        <a href="#next"><%= image_tag 'arrow-gray.png' %></a>
      </div>
    </div>
  </div>
</section>

<section class="contact-mid" id="next">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h2>EMAIL</h2>
        <hr>
        <p>info@miamiqosta.com</p>
      </div>
      <div class="col-sm-4">
        <h2>ADDRESS</h2>
        <hr>
        <p>9537 Harding Avenue Surfside<br>Miami, FL 33154</p>
      </div>
      <div class="col-sm-4">
        <h2>PHONE</h2>
        <hr>
        <p>+1.786.205.8800  (Eng | Esp)<br>+1.786.209.4673  (Eng | Rus | Swe)</p>
      </div>
    </div>
  </div>
</section>
<section class="contact-arrow">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p><i class="fa fa-caret-down fa-4x"></i></p>
      </div>
    </div>
  </div>
</section>

<section class="contact-form">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @contact.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @contact.last %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @contact.cellphone %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @contact.interest %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>