config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :contacts

  resources :developments

  get '/new-developments' => 'developments#new_developments_index'

  root to: 'pages#home'

  get '/concierge' => 'pages#concierge'
  get '/concierge/sky-concierge' => 'pages#sky'
  get '/concierge/ocean-concierge' => 'pages#ocean'
  get '/concierge/executive-concierge' => 'pages#executive'
  get '/concierge/exotic-concierge' => 'pages#exotic'
  get '/concierge/time-management' => 'pages#time'
  get '/investments' => 'pages#investments'
  get '/investments/how-to-buy-a-house' => 'pages#house'
  get '/integral-service' => 'pages#integral'
  get '/integral-service/legal' => 'pages#legal'
  get '/integral-service/visa-eb5' => 'pages#visa'
  get '/integral-service/eb5-program' => 'pages#eb5'
  get '/integral-service/financing' => 'pages#financing'
  get '/team' => 'pages#team'
  get '/contact' => 'contacts#new', as: 'contact_email'
  get '/thanks' => 'pages#thanks'

end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <div class="pull-left">
        <p>© 2015 - All Rights Reserved</p>
      </div>
      <div class="pull-right">
        <p>Designed with love by <a href="http://stiltmedia.com" target="_blank">stiltmedia</a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="header-3">
  <div class="container">
    <div class="row">
      <nav class="navbar col-sm-12 navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <%= link_to image_tag('logo.svg', class: 'logo-top'), root_path %>
        </div>
      </nav>
    </div>
  </div>
  <div class="header-background"></div>
</header>

app/views/layouts/_language.html.erb
<div>
  <select class="cs-select cs-skin-elastic">
    <option value="" disabled selected>Language</option>
    <option style="padding:2em 0em 0em 1em;">Coming Soon</option>
    <!-- <option value="spain" data-class="flag-spain">Español</option>
    <option value="france" data-class="flag-france">français</option>
    <option value="brazil" data-class="flag-brazil">Português</option>
    <option value="russia" data-class="flag-russia">русский</option> -->
  </select>
</div>

app/views/layouts/_menu_button.html.erb
<button id="ody-trigger" type="button" class="tcon tcon-menu--xbutterfly" aria-label="toggle menu">
  <h3 class="menu-title">Menu</h3>
  <span class="tcon-menu__lines" aria-hidden="true"></span>
</button>

app/views/layouts/_navlinks.html.erb
<div class="ody-menu">
  <!-- ODY MAIN MENU -->
  <ul class="ody-main-menu">
    <li><%= link_to 'HOME', root_path %></li>
    <li><a href="#" id="dropdown">DEVELOPMENTS</a>
      <ul>
        <!-- <li><%# link_to 'OVERVIEW', developments_path %></li> -->
        <li><%= link_to 'NEW DEVELOPMENTS', new_developments_path %></li>
      </ul>
    <li><a href="#" id="dropdown2">CONCIERGE</a>
      <ul>
        <li><%= link_to 'MAIN', concierge_path %></li>
        <li><%= link_to 'SKY CONCIERGE', concierge_sky_concierge_path %></li>
        <li><%= link_to 'OCEAN CONCIERGE', concierge_ocean_concierge_path %></li>
        <li><%= link_to 'EXECUTIVE CONCIERGE', concierge_executive_concierge_path %></li>
        <li><%= link_to 'EXOTIC CONCIERGE', concierge_exotic_concierge_path %></li>
        <li><%= link_to 'TIME MANAGEMENT', concierge_time_management_path %></li>
      </ul>
    <li><a href="#" id="dropdown3">INVESTMENTS</a>
      <ul>
        <li><%= link_to 'MAIN', investments_path %></li>
        <li><%= link_to 'HOW TO BUY A HOUSE', investments_how_to_buy_a_house_path %></li>
      </ul>
      <li><a href="#" id="dropdown4">INTERGRAL SERVICE</a>
        <ul>
          <li><%= link_to 'MAIN', integral_service_path %></li>
          <!-- <li><%# link_to 'LEGAL ADVICE', integral_service_legal_path %></li> -->
          <li><%= link_to 'VISA EB-5', integral_service_visa_eb5_path %></li>
          <li><%= link_to 'EB-5 VISA INVESTOR PROGRAM', integral_service_eb5_program_path %></li>
          <li><%= link_to 'FINANCING', integral_service_financing_path %></li>
        </ul>
    <li><%= link_to 'TEAM', team_path %></li>
    <li><%= link_to 'CONTACT', contact_email_path %></li>
  </ul>
</div>

app/views/layouts/_preloader.html.erb
<!-- END SCRIPTS + CSS -->

<!-- BEGIN THE LOADING SCREEN -->
<div id="bonfire-pageloader">

	<!-- BEGIN THE ICON -->
	<div class="bonfire-pageloader-icon">
		<%= image_tag 'logo.png' %>
		<br>
		<hr>
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
			 width="512px" height="512px" viewBox="0 0 512 512" enable-background="new 0 0 512 512" xml:space="preserve">
		<path id="loading-12-icon" d="M291,82.219c0,16.568-13.432,30-30,30s-30-13.432-30-30s13.432-30,30-30S291,65.65,291,82.219z
			 M261,404.781c-15.188,0-27.5,12.312-27.5,27.5s12.312,27.5,27.5,27.5s27.5-12.312,27.5-27.5S276.188,404.781,261,404.781z
			 M361.504,113.167c-4.142,7.173-13.314,9.631-20.487,5.489c-7.173-4.141-9.631-13.313-5.49-20.487
			c4.142-7.173,13.314-9.631,20.488-5.489C363.188,96.821,365.645,105.994,361.504,113.167z M188.484,382.851
			c-14.348-8.284-32.697-3.368-40.98,10.98c-8.285,14.349-3.367,32.696,10.98,40.981c14.35,8.283,32.697,3.367,40.98-10.981
			C207.75,409.482,202.834,391.135,188.484,382.851z M421.33,184.888c-8.368,4.831-19.07,1.965-23.901-6.404
			c-4.832-8.368-1.965-19.07,6.404-23.902c8.368-4.831,19.069-1.964,23.9,6.405C432.566,169.354,429.699,180.056,421.33,184.888z
			 M135.399,329.767c-8.285-14.35-26.633-19.266-40.982-10.982c-14.348,8.285-19.264,26.633-10.979,40.982
			c8.284,14.348,26.632,19.264,40.981,10.98C138.767,362.462,143.683,344.114,135.399,329.767z M436.031,277.249
			c-11.044,0-20-8.953-20-19.999c0-11.045,8.955-20.001,20.001-20.001c11.044,0,19.999,8.955,19.999,20.002
			C456.031,268.295,447.078,277.249,436.031,277.249z M115.97,257.251c-0.001-16.57-13.433-30.001-30.001-30.002
			c-16.568,0.001-29.999,13.432-30,30.002c0.001,16.566,13.433,29.998,30.001,30C102.538,287.249,115.969,273.817,115.97,257.251z
			 M401.333,364.248c-10.759-6.212-14.446-19.97-8.234-30.73c6.212-10.759,19.971-14.446,30.731-8.233
			c10.759,6.211,14.445,19.971,8.232,30.73C425.852,366.774,412.094,370.46,401.333,364.248z M135.398,184.736
			c8.285-14.352,3.368-32.698-10.98-40.983c-14.349-8.283-32.695-3.367-40.981,10.982c-8.282,14.348-3.366,32.696,10.981,40.981
			C108.768,204,127.115,199.082,135.398,184.736z M326.869,421.328c-6.902-11.953-2.807-27.242,9.148-34.145
			s27.243-2.806,34.146,9.149c6.902,11.954,2.806,27.243-9.15,34.145C349.059,437.381,333.771,433.284,326.869,421.328z
			 M188.482,131.649c14.352-8.286,19.266-26.633,10.982-40.982c-8.285-14.348-26.631-19.264-40.982-10.98
			c-14.346,8.285-19.264,26.633-10.98,40.982C155.787,135.017,174.137,139.932,188.482,131.649z"/>
		</svg>
	</div>
	<!-- END THE ICON -->


</div>
<!-- END THE LOADING SCREEN -->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>

  <title>MiamiQosta</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="msvalidate.01" content="FC011CE0105FCDEF96CA6CF4983F14D2" />

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-61911497-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>

  <%= render 'layouts/preloader' %>
  <%= render 'layouts/menu_button' %>
  <%= render 'layouts/language' %>




    <%= render 'layouts/header' %>
  <!-- <div class="page-wrapper"> -->
    <div class="ody-content">

      <%= render 'layouts/navlinks' %>
      <div id="bkg-overlay"></div>

      <%= yield %>

      <footer class="footer-2 bg-black">
        <%= render 'layouts/footer' %>
      </footer>

    </div>
  <!-- </div> -->


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script>

  $( "#ody-trigger" ).click(function() {
    $( "#bkg-overlay" ).toggle();
  });
  $( "#ody-trigger" ).click(function() {
    $( "body" ).toggleClass("stay-still");
  });

    (function() {
      [].slice.call( document.querySelectorAll( 'select.cs-select' ) ).forEach( function(el) {
        new SelectFx(el);
      } );
    })();


    (function($) {
      $('.development-residence,.development-penthouse, .development-area, .development-featured, .development-amenities, .development-services, .header-15-sub-home, .project-home, .development-btm, .concierge-1, .concierge-2, .concierge-3, .concierge-4, .concierge-5, .concierge-6, .concierge-7, .concierge-8, .concierge-9, .sky, .sky-info, .ocean, .ocean-info, .executive, .executive-info, .exotic, .exotic-info, .time, .time-info, .invest-1, .invest-2, .invest-3, .house, .house-info, .integral-1, .integral-2, .integral-3, .integral-4, .integral-5, .integral-6, .legal, .legal-info, .visa, .visa-2, .visa-4, .visa-5, .eb5, .eb5-2, .finance, .finance-info').each(function() {
        if (! isMobile.any() ) {
          $(this).parallax('50%', .3, true);
        } else {
          $(this).css('background-attachment', 'initial')
        }
      })
    }(jQuery));


    // Scroll to id
    $(function() {
      $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
          var target = $(this.hash);
          target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
          if (target.length) {
            $('html,body').animate({
              scrollTop: target.offset().top
            }, 1000);
            return false;
          }
        }
      });
    });

    jQuery(window).resize(function(){
       resizenow();
    });
    function resizenow() {
      var browserwidth = jQuery(window).width();
      var browserheight = jQuery(window).height();
      jQuery('.bonfire-pageloader-icon').css('right', ((browserwidth - jQuery(".bonfire-pageloader-icon").width())/2)).css('top', ((browserheight - jQuery(".bonfire-pageloader-icon").height())/2));
    };
    resizenow();

  </script>



</body>
</html>